// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-copy-cleaned-bibtex'
  | 'message-error-export-failed'
  | 'message-error-no-selection'
  | 'message-success-copied';
